// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbvUvKSt-LJwaJKxJusNk-Hyz4bZuUE-c',
    appId: '1:779104110367:web:7b73b6beeb1466ef37122a',
    messagingSenderId: '779104110367',
    projectId: 'disaster-management-app-d6820',
    authDomain: 'disaster-management-app-d6820.firebaseapp.com',
    storageBucket: 'disaster-management-app-d6820.firebasestorage.app',
    measurementId: 'G-7QLS6HHCCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdOCTqBC6p2TuIV8M8yez-VZ5t1PJU9ns',
    appId: '1:779104110367:android:d655de42bb46f54937122a',
    messagingSenderId: '779104110367',
    projectId: 'disaster-management-app-d6820',
    storageBucket: 'disaster-management-app-d6820.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVqhev4dJs7ql_XPYhX-2-nO1KNlZd6d8',
    appId: '1:779104110367:ios:223bc269424de33b37122a',
    messagingSenderId: '779104110367',
    projectId: 'disaster-management-app-d6820',
    storageBucket: 'disaster-management-app-d6820.firebasestorage.app',
    iosBundleId: 'com.example.disasterManagementApp',
  );
}
